### PR TITLE
Fix issue #14 where set tile at does not update 3D map

### PR DESCRIPTION
**Pull request by megabyte6**

### CODE REVIEW

**Comment by megabyte6** [comment]
@AqeeAqee I implemented the fix for #14 that I thought was best since you can't inject code into a built-in function. I added the function in the 3D Render block menu that matches the one built in the Scene menu. I tried to follow your code style and used similar formatting for the doc page. I did my best to match both your doc pages as well as the original [set tile at location] block on MakeCode's docs page. If there's anything you want changed just let me know and I'd be happy to make the change.

Additionally, I was wondering if it was alright to update the `targetVersions` in `pxt.json`. MakeCode Arcade automatically updated the `target` so I figured it would be good to update the rest as well. I'm not sure if you kept the version at that particular release because of some compatibility reason so I only pushed the change to `targetVersions.target` that was automatically done and nothing else. If there is no reason for keeping it at the current version, I'd be happy to update that as well.

**Comment by AqeeAqee** [comment]
Hi, @megabyte6 !

Sorry for late response, I just happend to see this without any notice from github.

Thanks allocate this issue and make this full solution, and even help docs provided also.
May I have an idea, that a little differance implement. How about provide a "Refresh Map" (or re-cache or something like) block, which doesn't call the "tiles.setTileAt(loc, tile)", just re-load the map data. User call " tiles.setTileAt(loc, tile)" at their code with official block. So there would not be 2 "same" setTileAt blocks, that might make users confused. And also "Refresh Map" block can be re-used in other situation in future. If you agree, would you mind push a new PR? As you have provided a full solution already, it's fine for me to merge this one also.

Don't worry about the version update, it is automatic and mandatory by Makecode.

Thanks for your contribution for this extension!

**Comment by megabyte6** [comment]
@AqeeAqee that's so strange that GitHub didn't send you a notification :disappointed:.

I like your idea for adding a "Refresh Map" block. I was wondering if it would be possible to add a sort of "hook" into MakeCode's `[set tile at pos]` block so it could automatically refresh the 3D tilemap. I won't try implementing it now since it is just an idea. Let me know what you think about it.

Regardless, I agree with your solution and I'll try to have a fix for that over the next day.

**Comment by AqeeAqee** [comment]
Hi, @megabyte6 !
Have no good solution to inject codes into existed functions/methods, except override class instance, which would lead to issues when original codes updated. 
Thanks for your[ new PR #17](https://github.com/AqeeAqee/pxt-raycasting/pull/17), that's ideal solution right now, I think, and it has been merged. This PR will be closed.
Thanks again for your contribution!

**Pull request closed without merging**
