### PR TITLE
Add refresh tilemap block

### PR DESCRIPTION
**Pull request by megabyte6**
Implement proposed fix for #15

### CODE REVIEW

**Comment by AqeeAqee** [comment]
Hi, @megabyte6 !
Thanks for your new PR, it looks nice, and has been merged.
Thanks again for your contribution.

**Comment by megabyte6** [comment]
@AqeeAqee thanks for merging my changes.

How do updates and versioning work for MakeCode Arcade extensions? I noticed it has been a while since the merge and MakeCode Arcade still uses the old code. I briefly looked into it and found some [documentation on MakeCode with GitHub releases](https://arcade.makecode.com/github/release). Since I don't have permission to the [main repository for ptx-raycasting](https://github.com/AqeeAqee/pxt-raycasting), could you publish a release so MakeCode Arcade detects the updates?

On a side note, I noticed that in your [commits for updating the version](https://github.com/AqeeAqee/pxt-raycasting/commit/865c87b6439905b33a6f9096ec1d479e5a4304bd) that you update `pxt.json`, `assets/version.txt`, and `assets/js/binary.js`. I assume `assets/js/binary.js` is done automatically. As for `pxt.json` and `assets/version.txt`, which ones need to be updated manually or are they both updated automatically? I had previously manually updated `pxt.json` but not `assets/version.txt`.

**Comment by megabyte6** [comment]
@AqeeAqee just giving you another mention. I haven't heard back in a little while, but I was still hoping to get the version in MakeCode Arcade updated. Cheers!

**Comment by megabyte6** [comment]
@AqeeAqee giving this another bump :+1:

**Pull request merged**
